server {
    listen 80;
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /Android_13.zip { 
        alias /var/www/html/HON660-T-96.00.04-\\(0061\\).zip;
        add_header Content-Type application/zip;
        add_header Content-Disposition "attachment; filename=Android_13.zip";
        expires 30d;
        access_log off;  
    }
}
