.POSIX:
.SUFFIXES:
all: game
game: resource file
	echo -e "let's play !!!"
resource: 
	echo -e "A tutorial on portable makefiles"
	echo -e "http://nullprogram.com/blog/2017/08/20/"
file:
	touch file
	echo 'Use make or die' >> file
clean:
	rm -f file